import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import apiImages from "../services/baseImages";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [url, setUrl] = useState("");
  const [imagesList, setImagesList] = useState([]);

  function searchImages() {
    console.log("valor", url);
    const results = apiImages.get(`/${url}`);
    results.then((res) => {
      console.log("RESULTS::::", res.data);
      setImagesList(res.data);
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo ao <a href="https://nextjs.org">DCatch!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div>
          <input
            type="text"
            placeholder="url"
            onChange={(e) => setUrl(e.target.value)}
          />
          <button onClick={searchImages}>Click</button>
        </div>

        <div className={styles.containerImages}>
          {imagesList.map((item) => (
            <img className={styles.imageItem} key={item.src} src={item.src} />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
